stages:             # these stages (jobs) form the CICD pipeline
  - build           # your original build stage
  - test            # your original test stage
  - deploy          # your original deploy stage
  - mavenbuild      # this is a JOB to build your Springboot application
  - maventest       # this is a JOB to run tests in your Springboot application (it's okay you don't have any tests for now)
  - mavendeploy     # this is a JOB to deploy your Springboot application on your server
  - androidbuild    # this is a JOB to build your Android application
  - androidtest     # this is a JOB to run tests in your Android application (it's okay you don't have any tests for now)

maven-build:            
  stage: mavenbuild     
  tags:                 
    - backend_tag
  script:               
    - cd Backend        
    - mvn package       
  artifacts:            
    paths:
      - Backend/target/*.jar 
  only:
    refs:
      - main            
    changes:
      - Backend/**/*    

maven-test:             
  stage: maventest     
  tags:
    - backend_tag
  script:
    - cd Backend       
    - mvn test         
  only:
    refs:
      - main            
    changes:
      - Backend/**/*    

auto-deploy:
  stage: mavendeploy    
  tags:
    - backend_tag
  script:               
    - cd Backend        
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - main            
    changes:
      - Backend/**/*    

