stages:             # these stages (jobs) form the CICD pipeline
  - mavenbuild      # this is a JOB to build your Springboot application
  - maventest       # this is a JOB to run tests in your Springboot application (it's okay you don't have any tests for now)
  - mavendeploy     # this is a JOB to deploy your Springboot application on your server
  - androidbuild    # this is a JOB to build your Android application
  - androidtest     # this is a JOB to run tests in your Android application (it's okay you don't have any tests for now)

maven-build:
  stage: mavenbuild
  tags:
    - backend_tag
  script:
    - cd Backend
    - mvn package
    # - export JAVA_HOME=/usr/lib/jvm/jre-17-openjdk-17.0.11.0.9-2.el9.x86_64
    # - export PATH=$JAVA_HOME/bin:$PATH
  artifacts:
    paths:
      - Backend/target/*.jar
  only:
    refs:
      - main
    changes:
      - Backend/**/*

maven-test:             
  stage: maventest     
  tags:
    - backend_tag
  script:
    - cd Backend       
    - mvn test         
  only:
    refs:
      - main            
    changes:
      - Backend/**/*    

auto-deploy:
  stage: mavendeploy    
  tags:
    - backend_tag
  script:               
    - cd Backend        
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - main            
    changes:
      - Backend/**/*    

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
   - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/CyDropFrontend/gradlew
  script:
    - cd Frontend/CyDropFrontend  
    - ./gradlew build
  only:
    refs:
      - main
    changes:
      - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - android_tag
  before_script:                   # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/CyDropFrontend/gradlew
  script:
    - cd Frontend/CyDropFrontend                  # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew test
  only:
    refs:
      - main
    changes:
      - Frontend/**/*

