stages:             # these stages (jobs) form the CICD pipeline
  - build           # your original build stage
  - test            # your original test stage
  - deploy          # your original deploy stage
  - mavenbuild      # this is a JOB to build your Springboot application
  - maventest       # this is a JOB to run tests in your Springboot application (it's okay you don't have any tests for now)
  - mavendeploy     # this is a JOB to deploy your Springboot application on your server
  - androidbuild    # this is a JOB to build your Android application
  - androidtest     # this is a JOB to run tests in your Android application (it's okay you don't have any tests for now)

build-job:
  stage: build
  tags:
    - backend_tag
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  tags:
    - backend_tag
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  tags:
    - backend_tag
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  tags:
    - backend_tag
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production

maven-build:            
  stage: mavenbuild     
  tags:                 
    - springboot_tag    
  script:               
    - cd Backend        
    - mvn package       
  artifacts:            
    paths:
      - Backend/target/*.jar 
  only:
    refs:
      - main            
    changes:
      - Backend/**/*    

maven-test:             
  stage: maventest     
  tags:
    - springboot_tag   
  script:
    - cd Backend       
    - mvn test         
  only:
    refs:
      - main            
    changes:
      - Backend/**/*    

auto-deploy:
  stage: mavendeploy    
  tags:
    - springboot_tag    
  script:               
    - cd Backend        
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - main            
    changes:
      - Backend/**/*    

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild              
  tags:
    - android_tag                   
  before_script:                   
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend                   
    - ./gradlew build               
  only:
    refs:
      - main                        
    changes:
      - Frontend/**/*               

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest               
  tags:
    - android_tag                   
  before_script:                   
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend                  
    - ./gradlew test               
  only:
    refs:
      - main                        
    changes:
      - Frontend/**/*
